### PR TITLE
Migrate to Dart 2.12 with null-safety

### PR DESCRIPTION
**Pull request by dumazy**
Set minimum SDK to >= 2.12.0 and applied type changes to support null-safety.
The version was updated to 2.0.0 as this might have breaking changes.

### CODE REVIEW

**Comment by dumazy** [comment]
The test for running on Dart 2.0.0 (test-legacy-sdk) fails in GitHub Actions, as expected.
This is a major update which depends on a higher version of Dart.

**Review by srawlins — APPROVED** [review]
I love it.

**Comment by dumazy** [comment]
Thanks for accepting this PR.
What are the next steps before we can see a new release? Is there anything I can help with?

**Comment by srawlins** [comment]
Just published. Thanks again!

**Pull request merged**
